environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
matrix:
  fast_finish: true
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
test_script:
  - npm run test:eslint
build: off
