environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
matrix:
  fast_finish: true
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
before_test:
  - npm start && sleep 15
build: off
