version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:7890c87cc891d2338281c772ca90c2c30e1df1fbe348c92a28f0638e36f993a9
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
