version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:677d670ee7343a7eb1d37326a230191b9f4f65d86d514aa77cba9de9cce8a09e
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
