version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16-stretch-browsers@sha256:155bed1fcf339a069fb43dbbf522d9bcffc533edcbbf83665ca856c43d9d7d35
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
