version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:f13abce5cd0f1ca3b09475630603621a37b950418981aed03bea9b3b8bf83261
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
