version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:0beb88e8de81dfe266fd4dd56062c4bef76926df8e4770044f28a09a28cb0f20
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
