version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:0d0029afe8595542e65d72f8674d7fda05f0a4301358c9d34d44e94bb3c8a2c3
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
