version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:37172af7c9a51fb7d5cedcd4f6ca4cc1baddb00d6047f202506ee786dbd755d9
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
