version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:80c0af4f709ad493f0786435b53a3019c23c60451965d0e56548b0135acafe34
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
