version: 2
jobs:
  build:
    docker:
      - image: circleci/node:17-stretch-browsers@sha256:d9454b5db585bf0a3b56b4003cc6fe1310b1c425eaa80cdf090bf3a5352dee99
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
