version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:9954909140c42b14888979042b2a7c40277edd66f59fcdb9ea1d34acfb7231a9
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
