version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:21d76ea64b8236cf435ae8b2e53f23c2b97adccee87d015531d884f2463a1f2d
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
