version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16-stretch-browsers@sha256:a9ccefc04be75ffbe51edd023ac613ae79f0f35a86660cda3ae46517ff7b9bc5
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
