version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:0b3d8ac46fc171c2af9222709f15afdc67a97256a459ac2d1e798cc84f6e710e
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
