version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:31006f5fe9d8b400878fd439f1d402a0e7ded57a19e0491d1c6dcd29c482bd1c
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
