version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-stretch-browsers@sha256:46b0bedc9336a81b5cdc7cef2052de122ac1df74881c18b37ff551031d6d35ee
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run:
          name: start
          command: npm run start
          background: true
      - run: sleep 15
      - run: npm run test
